# Generated by Django 3.0.5 on 2020-04-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueseria', '0002_hamburguesa_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesa',
            name='ingredientes_hamburguesa',
            field=models.ManyToManyField(to='hamburgueseria.Ingrediente'),
        ),
    ]
