# Generated by Django 3.0.5 on 2020-05-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueseria', '0003_hamburguesa_ingredientes_hamburguesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
