# Generated by Django 3.0.5 on 2020-05-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueseria', '0004_auto_20200504_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hamburguesa',
            old_name='ingredientes_hamburguesa',
            new_name='ingredientes',
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='imagen',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
